version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    networks: [app-network]
    ports:
      - '8990:80'
    environment:
      SSL_MODE: "off"
    volumes:
        - type: bind
          source: .
          target: /var/www/html

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '8991:3306'
    env_file: .env
    volumes:
      - 'cursuskit-mysql:/var/lib/mysql'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks: [app-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

volumes:
  cursuskit-mysql:
    driver: local

networks:
  app-network:
    driver: bridge
