services:
  cursuskit-app:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    env_file: '.env.prod'
    ports:
      - '8990:80'
    depends_on:
      - cursuskit-db
    networks:
      - cursuskit
    environment:
      DB_HOST: 'database'
      REDIS_HOST: 'cache'
    healthcheck:
      test:
        - CMD
        - service
        - nginx
        - status

  cursuskit-db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '8991:3306'
    env_file: '.env.prod'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'cursuskit-mysql:/var/lib/mysql'
    networks:
      - cursuskit
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  cursuskit-redis:
    image: 'redis:alpine'
    volumes:
      - 'cursuskit-redis:/data'
    networks:
      - cursuskit
    ports:
      - '8992:6379'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  cursuskit:
    driver: bridge

volumes:
  cursuskit-mysql:
    driver: local
  cursuskit-storage:
    driver: local
  cursuskit-logs:
    driver: local
  cursuskit-app:
    driver: local
  cursuskit-redis:
    driver: local